CREATE TABLE USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(15) NOT NULL,
	IS_ROOM BOOLEAN,
);
CREATE UNIQUE INDEX PRIMARY_KEY_61 ON USERS (ID);

CREATE TABLE MESSAGES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CONTENT VARCHAR(500),
	SENT_DATE BIGINT NOT NULL,
	"TYPE" SMALLINT NOT NULL,
	SENDER_ID INTEGER NOT NULL,
	RECEIVER_ID INTEGER NOT NULL,
	FWD_USER_ID INTEGER,
	SENT BOOLEAN,
);
CREATE INDEX MESSAGES_FK_FWD_INDEX_8 ON MESSAGES (FWD_USER_ID);
CREATE INDEX MESSAGES_FK_RECEIVER_INDEX_8 ON MESSAGES (RECEIVER_ID);
CREATE INDEX MESSAGES_FK_SENDER_INDEX_8 ON MESSAGES (SENDER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON MESSAGES (ID);
