-- ID Sequences
CREATE SEQUENCE PUBLIC.SEQ_USER;
CREATE SEQUENCE PUBLIC.SEQ_MESSAGE;

-- PUBLIC.USERS definition

-- Drop table

-- DROP TABLE PUBLIC.USERS;

CREATE TABLE PUBLIC.USERS (
	ID INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_USER" NOT NULL,
	USERNAME VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(15) NOT NULL,
	IS_ROOM BOOLEAN,
	CONSTRAINT USERS_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_61 ON PUBLIC.USERS (ID);

-- PUBLIC.MESSAGES definition

-- Drop table

-- DROP TABLE PUBLIC.MESSAGES;

CREATE TABLE PUBLIC.MESSAGES (
	ID INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_MESSAGE" NOT NULL,
	CONTENT VARCHAR(500),
	SENT_DATE BIGINT NOT NULL,
	"TYPE" SMALLINT NOT NULL,
	SENDER_ID INTEGER NOT NULL,
	RECEIVER_ID INTEGER NOT NULL,
	FWD_USER_ID INTEGER,
	SENT BOOLEAN,
	CONSTRAINT MESSAGES_PK PRIMARY KEY (ID)
);
CREATE INDEX MESSAGES_FK_FWD_INDEX_8 ON PUBLIC.MESSAGES (FWD_USER_ID);
CREATE INDEX MESSAGES_FK_RECEIVER_INDEX_8 ON PUBLIC.MESSAGES (RECEIVER_ID);
CREATE INDEX MESSAGES_FK_SENDER_INDEX_8 ON PUBLIC.MESSAGES (SENDER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON PUBLIC.MESSAGES (ID);


-- PUBLIC.MESSAGES foreign keys

ALTER TABLE PUBLIC.MESSAGES ADD CONSTRAINT MESSAGES_FK_FWD FOREIGN KEY (FWD_USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.MESSAGES ADD CONSTRAINT MESSAGES_FK_RECEIVER FOREIGN KEY (RECEIVER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.MESSAGES ADD CONSTRAINT MESSAGES_FK_SENDER FOREIGN KEY (SENDER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;