package ogr.user12043.talkOnLan.ui;

import ogr.user12043.talkOnLan.Main;
import ogr.user12043.talkOnLan.User;

/**
 * Created by user12043 on 31.07.2018 - 12:11
 * part of project: talk-onLan
 */
public class BuddyPanel extends javax.swing.JPanel {

    private User user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_message;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_name;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form Buddy
     */
    public BuddyPanel(User user) {
        initComponents();
        this.user = user;
        jLabel_name.setText(user.getUserName());
        jLabel_address.setText(user.getAddress().toString());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_name = new javax.swing.JLabel();
        jLabel_address = new javax.swing.JLabel();
        jButton_message = new javax.swing.JButton();

        jLabel_name.setFont(jLabel_name.getFont().deriveFont(jLabel_name.getFont().getSize() + 6f));
        jLabel_name.setText("name");

        jLabel_address.setFont(jLabel_address.getFont().deriveFont(jLabel_address.getFont().getSize() + 6f));
        jLabel_address.setText("address");

        jButton_message.setText("Message");
        jButton_message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_messageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_address)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_message)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_name)
                                        .addComponent(jLabel_address)
                                        .addComponent(jButton_message))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_messageActionPerformed
        Main.mainUI.getMessagePanelOfUser(user).setVisible(true);
    }//GEN-LAST:event_jButton_messageActionPerformed
}
