package ogr.user12043.talkOnLan.ui;

import ogr.user12043.talkOnLan.User;

import javax.swing.*;
import java.awt.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Created by user12043 on 31.07.2018 - 12:10
 * part of project: talk-onLan
 */
public class BuddiesPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private final Set<BuddyPanel> buddyPanels;
    private int yIndex = 0;

    /**
     * Creates new form BuddiesPanel
     */
    public BuddiesPanel() {
        initComponents();
        buddyPanels = new HashSet<>();
    }

    /**
     * Add new panel for new user
     *
     * @param user new user to add
     */
    public void addBuddy(User user) {
        GridBagConstraints c = new GridBagConstraints();
        c.anchor = GridBagConstraints.NORTH;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.gridx = 0;
        c.gridy = yIndex;
        c.weightx = 1.0d;
        c.weighty = 1.0d;
        BuddyPanel buddyPanel = new BuddyPanel(user);
        add(buddyPanel, c);
        buddyPanels.add(buddyPanel);
        c.gridy = yIndex + 1;
        add(new JSeparator(), c);
        yIndex += 2;
        revalidate();
    }

    /**
     * Overrided setEnabled() method to apply enabled state to included buddy panels
     *
     * @param enabled enabled state
     */
    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        // setEnabled child components also
        for (Component component : getComponents()) {
            component.setEnabled(enabled);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
}
