package ogr.user12043.talkOnLan.ui;

import ogr.user12043.talkOnLan.User;
import ogr.user12043.talkOnLan.util.Utils;

import java.awt.*;
import java.util.Date;

/**
 * Created by user12043 on 02.08.2018 - 08:45
 * part of project: talk-onLan
 */
public class MessageBox extends javax.swing.JPanel {
    private User user;
    private String message;
    private boolean own;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_left;
    private javax.swing.JLabel jLabel_right;
    private javax.swing.JTextArea jTextArea_content;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MessageBox
     */
    MessageBox(User user, String message, boolean own) {
        this.user = user;
        this.message = message;
        this.own = own;
        initComponents();
    }

    private String getDate() {
        return Utils.formatDate(new Date());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_left = new javax.swing.JLabel();
        jLabel_right = new javax.swing.JLabel();
        jTextArea_content = new javax.swing.JTextArea();

        setMaximumSize(new Dimension(300, Integer.MAX_VALUE));

        jLabel_left.setText(((own) ? user.getUserName() : Utils.formatDate(new Date())));

        jLabel_right.setText(((!own) ? user.getUserName() : Utils.formatDate(new Date())));

        jTextArea_content.setEditable(false);
        jTextArea_content.setColumns(50);
        jTextArea_content.setLineWrap(true);
        jTextArea_content.setText(message);
        jTextArea_content.setWrapStyleWord(true);
        jTextArea_content.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextArea_content, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_left)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel_right)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_left)
                    .addComponent(jLabel_right))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea_content, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

}
