package ogr.user12043.talkOnLan.ui;

import ogr.user12043.talkOnLan.model.Message;
import ogr.user12043.talkOnLan.util.Constants;
import ogr.user12043.talkOnLan.util.Properties;
import ogr.user12043.talkOnLan.util.Utils;

import javax.swing.*;
import java.awt.*;

/**
 * Created by user12043 on 02.08.2018 - 08:45
 * part of project: talk-onLan
 */
class MessageBox extends javax.swing.JPanel {
    private final Message message;
    private final boolean own;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_left;
    private javax.swing.JTextArea jTextArea_content;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MessageBox
     */
    MessageBox(Message message, boolean own) {
        this.message = message;
        this.own = own;
        initComponents();
        this.jLabel_left.setVisible(!own);
        if (own) {
            jTextArea_content.setBackground(jTextArea_content.getBackground().brighter());
        }
    }

    private String getUser() {
        if (message.getSender() == null) {
            return Properties.username;
        } else if ((message.getMessageType() != Constants.MSG_TYPE_FWD
                && message.getMessageType() != Constants.MSG_TYPE_FWD_PRIVATE)
                || message.getForwardedFrom() == null) {
            return message.getSender().getUsername();
        } else {
            return message.getForwardedFrom().getUsername();
        }
    }

    private String getDate() {
        return Utils.formatDate(message.getSentDate());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel_left = new javax.swing.JLabel();
        jTextArea_content = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel_time = new javax.swing.JLabel(getDate(), own ? SwingConstants.RIGHT : SwingConstants.LEFT);

        setMaximumSize(new Dimension(300, Integer.MAX_VALUE));

        jLabel_left.setText(getUser());

        jTextArea_content.setEditable(false);
        jTextArea_content.setColumns(25);
        jTextArea_content.setLineWrap(true);
        jTextArea_content.setText(message.getContent());
        jTextArea_content.setWrapStyleWord(true);
        jTextArea_content.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel_left)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jTextArea_content))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextArea_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
    }//GEN-END:initComponents

}
