package ogr.user12043.talkOnLan.ui;

import ogr.user12043.talkOnLan.User;
import ogr.user12043.talkOnLan.util.Utils;

import javax.swing.*;
import java.awt.*;
import java.util.Date;

/**
 * Created by user12043 on 02.08.2018 - 08:45
 * part of project: talk-onLan
 */
class MessageBox extends javax.swing.JPanel {
    private final User user;
    private final String message;
    private final boolean own;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_left;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JTextArea jTextArea_content;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MessageBox
     */
    MessageBox(User user, String message, boolean own) {
        this.user = user;
        this.message = message;
        this.own = own;
        initComponents();
        this.jLabel_left.setVisible(!own);
        if (own) {
            jTextArea_content.setBackground(Color.CYAN);
        }
    }

    private String getDate() {
        return Utils.formatDate(new Date());
    }

    private int getDateAlignment() {
        return own ? SwingConstants.RIGHT : SwingConstants.LEFT;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_left = new javax.swing.JLabel();
        jTextArea_content = new javax.swing.JTextArea();
        jLabel_time = new javax.swing.JLabel(getDate(), getDateAlignment());

        setMaximumSize(new Dimension(300, Integer.MAX_VALUE));

        jLabel_left.setText(user.getUserName());

        jTextArea_content.setEditable(false);
        jTextArea_content.setColumns(25);
        jTextArea_content.setLineWrap(true);
        jTextArea_content.setText(message);
        jTextArea_content.setWrapStyleWord(true);
        jTextArea_content.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_left)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextArea_content))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextArea_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_left))
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

}
