package ogr.user12043.talkOnLan.ui;

import ogr.user12043.talkOnLan.User;
import ogr.user12043.talkOnLan.net.MessageService;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.IOException;

/**
 * Created by user12043 on 31.07.2018 - 16:22
 * part of project: talk-onLan
 */
class MessagePanel extends javax.swing.JDialog {

    private final User user; // Remote user
    private int lineNumber;
    private boolean shiftPressed;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_send;
    private javax.swing.JPanel jPanel_dialogue;
    private javax.swing.JProgressBar jProgressBar_sending;
    private javax.swing.JScrollPane jScrollPane_content;
    private javax.swing.JScrollPane jScrollPane_dialogue;
    private javax.swing.JTextArea jTextArea_content;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MessagePanel
     *
     * @param parent parent frame
     * @param user   remote user
     */
    MessagePanel(Frame parent, User user) {
        super(parent, false);
        initComponents();
        lineNumber = 0;
        this.user = user;
        setTitle(user.getUserName() + " on " + user.getAddress());
        jProgressBar_sending.setVisible(false);
        jTextArea_content.requestFocusInWindow();
    }

    User getUser() {
        return user;
    }

    /**
     * Sends message to buddy
     */
    private void sendMessage(final String sendingMessage) {
        if (sendingMessage.isEmpty()) { // Ignore if empty
            setInputEnabled(true);
            return;
        }
        try {
            MessageService.sendMessage(user.getAddress(), sendingMessage); // Send message
            SwingUtilities.invokeLater(() -> {
                addMessage(sendingMessage, true); // Add message box to panel
                jTextArea_content.setText("");
                jTextArea_content.requestFocusInWindow();
                setInputEnabled(true);
            });
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Cannot send the message!", "ERROR", JOptionPane.ERROR_MESSAGE);
            SwingUtilities.invokeLater(() -> {
                jTextArea_content.setText(sendingMessage);
                setInputEnabled(true);
            });
        }
    }

    void receiveMessage(String message) {
        addMessage(message, false);
    }

    /**
     * Adds a {@link MessageBox} to panel for a message
     *
     * @param message message content
     * @param own     owning state
     */
    private void addMessage(String message, boolean own) {
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.gridy = lineNumber;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.weightx = 1.0d;
        constraints.insets = new Insets(0, 0, 20, 0);
        MessageBox messageBox = new MessageBox(user, message, own);
        jPanel_dialogue.add(messageBox, constraints);
        lineNumber++;
        revalidate();
    }

    private void setInputEnabled(boolean enabled) {
        jButton_send.setEnabled(enabled);
        jTextArea_content.setEnabled(enabled);
        jProgressBar_sending.setVisible(!enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_content = new javax.swing.JScrollPane();
        jTextArea_content = new javax.swing.JTextArea();
        jButton_send = new javax.swing.JButton();
        jScrollPane_dialogue = new javax.swing.JScrollPane();
        jPanel_dialogue = new javax.swing.JPanel();
        jProgressBar_sending = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 450));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jTextArea_content.setLineWrap(true);
        jTextArea_content.setRows(5);
        jTextArea_content.setWrapStyleWord(true);
        jTextArea_content.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea_contentKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea_contentKeyReleased(evt);
            }
        });
        jScrollPane_content.setViewportView(jTextArea_content);

        jButton_send.setText("Send");
        jButton_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendActionPerformed(evt);
            }
        });

        jScrollPane_dialogue.setAutoscrolls(true);

        jPanel_dialogue.setPreferredSize(jScrollPane_dialogue.getPreferredSize());
        jPanel_dialogue.setLayout(new java.awt.GridBagLayout());
        jScrollPane_dialogue.setViewportView(jPanel_dialogue);

        jProgressBar_sending.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane_dialogue)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton_send)
                                                .addGap(185, 185, 185)
                                                .addComponent(jProgressBar_sending, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane_content))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_dialogue, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton_send)
                                        .addComponent(jProgressBar_sending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendActionPerformed
        final String sendingMessage = jTextArea_content.getText().trim();
        setInputEnabled(false);
        new Thread(() -> sendMessage(sendingMessage)).start();
    }//GEN-LAST:event_jButton_sendActionPerformed

    private void jTextArea_contentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_contentKeyPressed
        final int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_SHIFT) {
            shiftPressed = true;
        } else if (keyCode == KeyEvent.VK_ENTER) {
            if (!shiftPressed) {
                jButton_sendActionPerformed(null);
            } else {
                jTextArea_content.append("\n");
            }
        }
    }//GEN-LAST:event_jTextArea_contentKeyPressed

    private void jTextArea_contentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_contentKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!shiftPressed) {
                jTextArea_content.setText("");
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_SHIFT) {
            shiftPressed = false;
        }
    }//GEN-LAST:event_jTextArea_contentKeyReleased

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        /*System.out.println("===================================================================================");
        System.out.println("window: " + getSize() + " | " + getPreferredSize());
        System.out.println("scroll pane: " + jScrollPane_dialogue.getSize() + " | " + jScrollPane_dialogue.getPreferredSize());
        System.out.println("panel: " + jPanel_dialogue.getSize() + " | " + jPanel_dialogue.getPreferredSize());
        System.out.println("===================================================================================");*/
    }//GEN-LAST:event_formComponentResized
}
